### ISSUE TITLE
Can't see Tilt

### ISSUE THREAD

**Issue by goose-ws** [mp-se/fermentrack-docker#17]
I'm running the container on a R.Pi3 with a fresh install of DietPi ARMv7 via:

```
docker run -d --name fermentrack --privileged --network host -v /home/goose/fermentrack/db:/home/fermentrack/fermentrack/db -v /home/goose/fermentrack/data:/home/fermentrack/fermentrack/data -v /home/goose/fermentrack/log:/home/fermentrack/fermentrack/log -v /dev:/dev mpse2/fermentrack-docker:latest
```

Setup goes fine, I select to not use GitHub updates. I'm able to add my controller without difficulty; however, my Tilt does not read. It's working, I'm about to see it via the Tilt mobile app. My bluetooth dongle works, scans fine outside of Docker.

Any ideas?

**Comment by mp-se** [comment]
Well there are a few things that could be wrong. You have the priviliged and host options sorted out so that should be ok. 

The other thing that is needed is for Python to have access to the device which is handled through the entrypoint.sh script in the docker container.  There is a troubleshooting wizard in Fermenentrack that will check the settings but that will report that the capabilitiy flags are missing even if they are set (bug in Fermentrack that has not yet been fixed). 

Can you check the output from the container when you start? If everything is ok you should have these 2 lines in the output;

>Checking if the container is running in priviliged mode
>Container is running in priviligied mode

If you dont get the second line the commands to set the capabilityflags failed and you probably have a linuxkernel/file system that does not support the capabilityflags with docker (from what have been able to figure out).

It could be other things that could be an issue but check these first and if they dont work I can do some testing on my end to see what we can do to troubleshoot the BT connectitiy. I dont own a tilt but have been testing this with a tilt simulator.

**Comment by goose-ws** [comment]
Yeah, logs confirm it's running privileged:

```
[goose@Kamal: ~ ] $ docker logs fermentrack
Checking if all required volumes are mounted correctly
Volume for data and database are mounted.
No secret file found, creating one
Generating SECRET_KEY and writing to fermentrack_django/secretsettings.py
secretsettings.py created!
Saving copy of secretsfile to db folder
Setting correct access rights on mounted volumes
Version of main linux packages installed in image:
****************************************************************
Debian GNU/Linux 10 \n \l

nginx version: nginx/1.14.2
Redis server v=5.0.3 sha=00000000:0 malloc=libc bits=32 build=1b271fe49834c463
Python 3.7.3
Image build date:
Sat Jan 30 14:39:20 UTC 2021
Starting NGINX
Starting REDIS
nginx: [warn] the "user" directive makes sense only if the master process runs with super-user privileges, ignored in /etc/nginx/nginx.conf:1
Checking if the container is running in priviliged mode
Container is running in priviligied mode
Starting Fermentrack
Collecting static files

269 static files copied to '/home/fermentrack/fermentrack/collected_static'.
Applying database migration
Operations to perform:
  Apply all migrations: admin, app, auth, contenttypes, database, external_push, firmware_flash, gravity, sessions
Running migrations:
  No migrations to apply.
Version/Source of fermentrack installed in image:
****************************************************************
origin  https://github.com/thorrak/fermentrack.git (fetch)
origin  https://github.com/thorrak/fermentrack.git (push)

commit b4e73786803e94eda4f0a2794d1e8ed8815fe933
Merge: 3f6a8a1 d592658
Author: John <thorrak@users.noreply.github.com>

    Tilt Pro Support (and other things)
****************************************************************
Starting circus deamon
[goose@Kamal: ~ ] $
```

And your requested `hostnamectl`:

```
[goose@Kamal: ~ ] $ hostnamectl
   Static hostname: Kamal.goose.ws
         Icon name: computer
        Machine ID: e6e4b4f3110a48198e09ef48fd82d14f
           Boot ID: 757904886b9b49b7b872c702e3ad9778
  Operating System: Raspbian GNU/Linux 10 (buster)
            Kernel: Linux 5.10.11-v7+
      Architecture: arm
[goose@Kamal: ~ ] $
```

I'm installing bare-metal Fermentrack right now, to ensure that it works on bare-metal, and it's not related to me using DietPi instead of Raspbian. If it's beneficial to work with a real Tilt, would you have any time/interest in debugging it over AnyDesk?

**Comment by mp-se** [comment]
If you go to the help page in fermentrack (?) in the menu and take a look at the logfile called fermentrack-process manager.log. Are there any errors or indication that a tilt has been found?

Can you also try the Troubleshoot tilt/bluetooth on the bottom of that page? It should be a warning connected to the capability flags but its just a wrong detection in the code. 

I've just done a quick test on my Pi3 with Buster and with my tilt-sim the connection worked. I noticed that I'm using kernel 5.4 but dont know if that makes a difference. 

If we cannot find anything there we need to do some troubleshooting on the linux cmdline.

**Comment by mp-se** [comment]
I found this guide that could be useful to att least see if it's working on the host. It should be possible to do the same commands in the docker image... I'm trying this out on my pio but it's damn slow to run docker... 

https://www.instructables.com/Reading-a-Tilt-Hydrometer-With-a-Raspberry-Pi/

**Comment by goose-ws** [comment]
I can't run the `hcitool` inside the docker container, but on the bare-metal host, I get a lot of devices. I'm not sure which is the Tilt.

![image](https://user-images.githubusercontent.com/874014/107425946-a3a19080-6aed-11eb-9303-f5a72833b919.png)

I know the Tilt is working, as I can read its data from my phone, at a further distance than the RasPi is.

The output of my entire `/log/fermentrack-processmgr.log`:

```
INFO:processmgr:Settings: Start delay: 2s, Sleep Interval: 15s, 
INFO:processmgr:New BrewPi device found: dev-1
INFO:processmgr:New Tilt device found: tilt-
```

The Troubleshoot Tilt page passes all checks, no issues with the `setcap` or any of the dependent packages.

As an aside, I'm unable to test using bare-metal Fermentrack, as it fails to correctly install on DietPi or Raspbian, for me. I get a 509 return from Nginx using the official/bare metal install on both OS variants.

**Comment by mp-se** [comment]
It looks like fermentrack has found the tilt according to the log.... so it should work... Can you test this on the standard raspian as well ? If you cant get it to work on bare metal there might be something strange with DietPi... I'm starting my day here so I will take a look after work at the code and see if I can put togehter some type of test code to test with.

**Comment by mp-se** [comment]
You can try this python script to see if the tilt can be detected... it works on my simulator... will try it in the docker container later tonight. its a modified version of this script; https://github.com/LinuxChristian/tilt2mqtt

#!/usr/bin/env python
#
# pip install requests PyBluez beacontools
#
import time
import logging as lg
import os
import json
from beacontools import BeaconScanner, IBeaconFilter, parse_packet, const
import requests

#
# Constants
#
sleep_interval = 10  # How often to listen for new messages in seconds

# Unique bluetooth IDs for Tilt sensors
TILTS = {
        'a495bb10c5b14b44b5121370f02d74de': 'Red',
        'a495bb20c5b14b44b5121370f02d74de': 'Green',
        'a495bb30c5b14b44b5121370f02d74de': 'Black',
        'a495bb40c5b14b44b5121370f02d74de': 'Purple',
        'a495bb50c5b14b44b5121370f02d74de': 'Orange',
        'a495bb60c5b14b44b5121370f02d74de': 'Blue',
        'a495bb70c5b14b44b5121370f02d74de': 'Yellow',
        'a495bb80c5b14b44b5121370f02d74de': 'Pink',
}

def callback(bt_addr, rssi, packet, additional_info):
    """Message recieved from tilt
    """
    print(additional_info)
    msgs = []
    color = "unknown"

    try:
        uuid = additional_info["uuid"]
        color = TILTS[uuid.replace('-','')]
    except KeyError:
        print("Unable to decode tilt color. Additional info was {}".format(additional_info))

    try:
        # Get and convert temperature
        temperature_farenheit = float(additional_info["major"])
        temperature_celsius = (temperature_farenheit - 32) * 5/9

        # Get and convert gravity
        specific_gravity = float(additional_info["minor"])/1000
        degree_plato = 135.997*pow(specific_gravity, 3) - 630.272*pow(specific_gravity, 2) + 1111.14*specific_gravity - 616.868

        data = {
            "specific_gravity_uncali": "{:.3f}".format(specific_gravity),
            "plato_uncali": "{:.2f}".format(degree_plato),
            "temperature_celsius_uncali": "{:.2f}".format(temperature_celsius),
            "temperature_farenheit_uncali": "{:.1f}".format(temperature_farenheit)
        }

        print( json.dumps(data) )
    except KeyError:
        print("Device does not look like a Tilt Hydrometer.")

scanner = BeaconScanner(callback)

scanner.start()
monitor = scanner._mon
while(1):
    time.sleep(sleep_interval)

**Comment by mp-se** [comment]
You can also run this from within the container. Place the file in one of the mounted directories, i.e data.

start a shell in the running container

docker exec -it <container name> /bin/bash

run these commands in the container

cd /home/fermentrack/fermentrack
source ../venv/bin/activate
pip install BeaconTools BeaconScanner
python /home/fermentrack/fermentrack/data/<script>.py

**Comment by goose-ws** [comment]
For anyone else who comes across this:

Changing the battery fixed it. I'm not sure how, as the bluetooth receiver is mounted on the outside of the chest freezer I use for fermentation, and could not pick up the Tilt. My phone was in my hand, 10 feet away from the chest freezer, and could. But lo and behold, a battery change fixed it.

**Comment by mp-se** [comment]
Great news, some issues are not what you first expect.
