### ISSUE TITLE
Synology NAS error

### ISSUE THREAD

**Issue by zeister** [mp-se/fermentrack-docker#23]
When i try to run your image on my  Synology NAS, I  am getting an error that  says "Volume  for  data and / or database is NOT mounted. Aborting startup ..." Any help would be greatly appreciated!

**Comment by mp-se** [comment]
You need to assign the 3 volumes in the container setup like this;  The mount path is the expected path in the image and the left side is a directory on a NAS volume. Log is not required but db and data is. 

![image](https://user-images.githubusercontent.com/51722613/111655890-4d212380-880a-11eb-8221-cf1b1f22371f.png)

**Comment by zeister** [comment]
Hi Magnus,
This fixed my problems getting it to start, thank you!!

Have you had any luck using a tiltbridge with this? I am unable to get 
it to work. When I navigate to 
http://ipofmysynology:portofcontainer/tiltbridge I get the following error:

*/{ "status": "failed", "message": "Malformed JSON - Unable to parse!" }/*


Again, thank you so much for your efforts and help!

-Cheers,
Frank

**Comment by mp-se** [comment]
I have not used a tilbridge but from what I understand it should communicate via WIFI. Can desribe in more detail where the error occurs and if possible past some output from relevant logs.

**Comment by mp-se** [comment]
I would expect its normal that you get an error message trying to navigate to the /tiltbridge URL on fermentrack, I would expect to get a json message with the tilt data.

**Comment by zeister** [comment]
Thanks again Magnus! 
for testing purposes, I setup a new traditional Fermentrack install onto a RiPi. TiltBridge was not working on that either. I ended reaching out to Thorrak and I updated to the latest version of the dev channel, 3/12. Tiltbridge then started working.
I then went back to my docker on my Synology and did the same update from inside of Fermentrack, and unfortunately Fermentrack has stopped working. Do you have any idea how to update to the latest dev version? I'm happy to share logs if it's helpful.

**Comment by mp-se** [comment]
It looks like there is a permission issue on the docker image that blocks the upgrade from working (only applies to the dev branch), it fails when trying to upgrade the python packages. It's not a difficult fix but it will take a some time for the build to finish. I can post an update when its done.

**Comment by mp-se** [comment]
The build should be done in about an hour and published to docker hub. It should fix the problem, I will verfify this tomorrow.

**Comment by zeister** [comment]
Awesome! I'll do a pull later tonight to see how it goes as well. Thanks
again!!

**Comment by mp-se** [comment]
It looks like there are more issues to be solved, I need to do some more testing in the next few days.

**Comment by mp-se** [comment]
Think I found my misstake, I missed the flag for appying rights for all subdirectories.

If you run this linux command in the docker container before you do the git upgrade it should work;
chown -R fermentrack:fermentrack venv

you should be in the /home/fermentrack directory when doing this.

**Comment by mp-se** [comment]
There is a new version now that fixes the problem correcly. If you confirm it works please close this issue.

**Comment by zeister** [comment]
Magnus,
Everything seems to be working as it relates to the updating to the dev branch. THANK YOU VERY MUCH!!
Unfortunately, I still can't get my tiltbridge to work, but I don't think that has anything to do with your docker image.

-Cheers!
