### ISSUE TITLE
Latest update breaks script/LCD

### ISSUE THREAD

**Issue by gizzygizmo** [mp-se/fermentrack-docker#31]
Latest update (April 5th) seems to break the script that updates LCD.  Debug connection works and returns results... however; getting error in main fermentrack status "Cannot receiveLCD text fromController/Script".

Rollback to previous container/gitcommit works.   Wiped everything and while i'm able to communicate to brewpi in diag the main communication script seems to be broken.

**Comment by mp-se** [comment]
Thanks for the update, i will take a look at it. There has been some restructuring in the april release so im not surprised that everything is not working. I spent a lot of time yesterday to the buildx process for arm to work....

**Comment by mp-se** [comment]
Looks like the april update breaks the whole docker setup since the it now works differently in a docker context. It will require some rework to get this working again.

**Comment by gizzygizmo** [comment]
I see the same... I was able to use the docker-compose.yml from the github of fermentrack nd modify it such that I got another docker instance going using the stacked docker fermentrack setup.  I had to modify a few of the .conf files to reference other services by "name" and created a separate network so I could only expose one port.   I'll paste what I have here... may be worth working with the author to have the 'official' fermtrack be less customized.  I see a lot of the containers are building custom images that may be extraneous.

Based on the work the author did, maintaining another image may not be worth the extra work.  Probably better to work with the author to make the official image more usable out-of-the-box with just a compose yml.

`version: '3.3'

volumes:
  postgres_data: {}
  postgres_data_backups: {}
  fermentrack_data: {}
  fermentrack_logs: {}

services:
  django:
    build:
      context: .
      dockerfile: ./compose/production/django/Dockerfile
    image: fermentrack_django
    container_name: fermentrack_django
    depends_on:
      - postgres
      - redis
    volumes:
      - /dev:/dev
      - fermentrack_data:/app/data:z
      - fermentrack_logs:/app/log:z
      - /var/run/dbus:/var/run/dbus
      - /var/run/avahi-daemon/socket:/var/run/avahi-daemon/socket
    env_file:
      - ./.envs/.production/.django
      - ./.envs/.production/.postgres
    command: ["/start", "--privileged"]
    privileged: true
    restart: unless-stopped
    networks:
      - backend

  postgres:
    build:
      context: .
      dockerfile: ./compose/production/postgres/Dockerfile
    image: fermentrack_postgres
    container_name: fermentrack_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
      - postgres_data_backups:/backups:z
    env_file:
      - ./.envs/.production/.postgres
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - backend

  redis:
    image: redis:6.0
    container_name: fermentrack_redis
    restart: unless-stopped
    volumes:
      - ./compose/production/redis/redis.conf:/usr/local/etc/redis/redis.conf
    networks:
      - backend

  nginx:
    build:
      context: .
      dockerfile: ./compose/production/nginx/Dockerfile
    image: fermentrack_nginx
    container_name: fermentrack_nginx
    depends_on:
      - django
    restart: unless-stopped
    volumes:
      - fermentrack_data:/data:z
    ports:
      - "8084:80"
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:`

**Comment by mp-se** [comment]
Well, my nas cant handle docker compose (multiple images) so its too much hassle for me to use the orginal one. I will need to fix this some how... now that i know what to look for it should be possible to find what i need to change

**Comment by mp-se** [comment]
Try the latest version on docker-hub it fixes the problem with brewpi but I have not yet had the time to test everything. I'm currently monitoring a fermentation so I will wait to update until this is finished.

**Comment by goose-ws** [comment]
Curious to know if this got fixed, as my install seems to be broken, still. I get the following error:

`standard_init_linux.go:219: exec user process caused: exec format error`

**Comment by mp-se** [comment]
The lcd error has been fixed in 0.8 and works on my setup. Your error looks more like the wrong cpu arch is used (wrong image for your setup)
