### ISSUE TITLE
Numpy

### ISSUE THREAD

**Issue by matthew-main** [mp-se/fermentrack-docker#38]
Hey,

getting an error message when trying to calibrate my iSpindel - The "numpy" python package is not available which is required for calibration.

I have tried install numpy for python and python 3 ( i have pip installed for both) "pip install numpy"

Any ideas?

Cheers

Matt

**Comment by mp-se** [comment]
Which image version are you using?

**Comment by matthew-main** [comment]
Raspberry Pi OS Lite
Release date: May 7th 2021
Kernel version: 5.10

curl -L install.fermentrack.com | bash

**Comment by mp-se** [comment]
So you are not using the docker image? 

If the problem is with the fermentrack installation script you should post the problem in that repository instead for correct support. 

https://github.com/thorrak/fermentrack

**Comment by matthew-main** [comment]
Sorry docker install in the script so thought it was the docker version.
